name: gh-pages
on:
  push:
    branches: [main]
  
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
        poetry-version: ["1.6.1"]
        node-version: ["18.x"]

    env:
      GH_PAGES: 1
      DEBUG: 1
      GRAPHRAG_LLM_TYPE: "azure_openai_chat"
      GRAPHRAG_EMBEDDING_TYPE: "azure_openai_embedding"
      GRAPHRAG_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      GRAPHRAG_API_BASE: ${{ secrets.GRAPHRAG_API_BASE }}
      GRAPHRAG_API_VERSION: ${{ secrets.GRAPHRAG_API_VERSION }}
      GRAPHRAG_LLM_DEPLOYMENT_NAME: ${{ secrets.GRAPHRAG_LLM_DEPLOYMENT_NAME }}
      GRAPHRAG_EMBEDDING_DEPLOYMENT_NAME: ${{ secrets.GRAPHRAG_EMBEDDING_DEPLOYMENT_NAME }}
      GRAPHRAG_CACHE_TYPE: "blob"
      GRAPHRAG_CACHE_CONNECTION_STRING: ${{ secrets.BLOB_STORAGE_CONNECTION_STRING }}
      GRAPHRAG_CACHE_CONTAINER_NAME: "cicache"
      GRAPHRAG_CACHE_BASE_DIR": "cache"
      GRAPHRAG_LLM_MODEL: gpt-3.5-turbo-16k
      GRAPHRAG_EMBEDDING_MODEL: text-embedding-ada-002
      # We have Windows + Linux runners in 3.10 and 3.11, so we need to divide the rate limits by 4
      GRAPHRAG_LLM_TPM: 45_000 # 180,000 / 4
      GRAPHRAG_LLM_RPM: 270 # 1,080 / 4
      GRAPHRAG_EMBEDDING_TPM: 87_500 # 350,000 / 4
      GRAPHRAG_EMBEDDING_RPM: 525 # 2,100 / 4
      GRAPHRAG_CHUNK_SIZE: 1200
      GRAPHRAG_CHUNK_OVERLAP: 0

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry ${{ matrix.poetry-version }}
        uses: abatilo/actions-poetry@v3.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}

      - name: Use Node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Yarn dependencies
        run: yarn install
        working-directory: docsite

      - name: Install Poetry dependencies
        run: poetry install

      - name: Install Azurite
        id: azuright
        uses: potatoqualitee/azuright@v1.1
  
      - name: Generate Indexer Outputs
        run: |
          poetry run poe test_smoke
          zip -jrm docsite/data/operation_dulce/dataset.zip tests/fixtures/min-csv/output/*/artifacts/*.parquet
        
      - name: Build Jupyter Notebooks
        run: poetry run poe convert_docsite_notebooks

      - name: Build docsite
        run: yarn build
        working-directory: docsite
        env:
          DOCSITE_BASE_URL: "graphrag"

      - name: List docsite files
        run: find docsite/_site

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.6.0
        with:
          branch: gh-pages
          folder: docsite/_site
          clean: true
