name: JavaScript CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  javascript-ci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 18.x

    steps:
      - name: Use Node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - uses: actions/checkout@v4

      - run: yarn install
        working-directory: docsite
        name: Install Dependencies

      - run: yarn build
        working-directory: docsite
        name: Build Docsite